#!/bin/sh

echo "Checking types..."
typecheck_output=$(npm run typecheck)

if [ $? -ne 0 ]; then
    echo "** ERROR: Type checking failed. Commit blocked. **"
    echo "$typecheck_output"
    exit 1
fi

echo "Linting..."
lint_output=$(npx biome lint ./src)

if [ $? -ne 0 ]; then
    echo "** ERROR: Lint checking failed. Commit blocked. **"
    echo "$lint_output"
    exit 1
fi

echo "Formatting..."
format_output=$(npx biome format ./src)

if [ $? -ne 0 ]; then
    echo "** ERROR: Format checking failed. Commit blocked. **"
    echo "$format_output"
    exit 1
fi

echo "Testing..."
test_output=$(env NODE_OPTIONS='--import tsx' npx vitest run)

if [ $? -ne 0 ]; then
    echo "** ERROR: Tests failed. Commit blocked. **"
    echo "$test_output"
    exit 1
fi

exit 0
